### ISSUE TITLE
Bug: 应使用相对而不是绝对

### ISSUE THREAD

**Issue by MingxuanGame** [HornCopper/Inkar-Suki#4]
在导入时，`sys.path.append`添加路径使用了绝对路径，应该改为使用相对路径
```python
sys.path.append(str(Path(__file__).parent.parent.parent / "tools"))
```

**Comment by HornCopper** [comment]
是这样的亲，如果不忙的话，可以顺手改了交pr吗（

**Comment by MingxuanGame** [comment]
> 是这样的亲，如果不忙的话，可以顺手改了交pr吗（

我躺平了，看star的时候顺手看到的（

用github的编辑器会有一大堆提交受不了（

**Comment by HornCopper** [comment]
> > 是这样的亲，如果不忙的话，可以顺手改了交pr吗（
> 
> 我躺平了，看star的时候顺手看到的（
> 
> 用github的编辑器会有一大堆提交受不了（

行吧，我自己写（（（

**Comment by HornCopper** [comment]
先close了，周末再写（（（

**Comment by HornCopper** [comment]
我改主意了，先挂着吧（x

**Comment by HornCopper** [comment]
行啊（

**Comment by HornCopper** [comment]
已修复（#5）
